### ISSUE TITLE
缺乏文件 无法运行

### ISSUE THREAD

**Issue by chizhu** [tongchangD/bert_for_corrector#7]
![image](https://user-images.githubusercontent.com/15606803/96214431-08206900-0fae-11eb-9918-8ead91c515ec.png)
可以提供config里面的这些文件吗 感谢！

**Comment by tongchangD** [comment]
Give me one afternoon to make sure the file is not related to the company's content, and I'll upload it immediately

**Comment by chizhu** [comment]
thanks



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tongchangD"<notifications@github.com&gt;; 
发送时间: 2020年10月16日(星期五) 下午2:06
收件人: "tongchangD/bert_for_corrector"<bert_for_corrector@noreply.github.com&gt;; 
抄送: "林智敏"<214416523@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tongchangD/bert_for_corrector] 缺乏文件 无法运行 (#7)





 
Give me one afternoon to make sure the file is not related to the company's content, and I'll upload it immediately

**Comment by tongchangD** [comment]
File has been uploaded.

**Comment by chizhu** [comment]
Thanks again, it helps me a lot.
